In [1]:
import requests
import pandas as pd
import datetime
import pytz

from bs4 import BeautifulSoup

In [2]:
def get_races(oRaces):
    return oRaces.find_all('a')

In [3]:
def get_mileage(oRace):
    return round(float(oRace.find_all_next('td')[3].contents[0].strip(' NM')))

In [4]:
def get_race_name(oRace):
    return oRace.contents[0]

In [5]:
def get_race_time(oRace):
    return datetime.datetime.fromisoformat(oRace.find_all_next('span')[1].contents[0]).astimezone(pytz.timezone('EST')).strftime('%A %d-%h %I:%M %p')

In [6]:
short_mileage = 50

In [7]:
r = requests.get('https://sarl.ingenium.net.au/index')

In [8]:
soup = BeautifulSoup(r.text, 'html.parser')
upcoming = soup.find('table')

In [9]:
data=[(get_race_name(race), get_mileage(race), get_race_time(race)) for race in get_races(upcoming)]

In [10]:
df=pd.DataFrame(data, columns=['Race', 'Mileage', 'Time'])
df

,Race,Mileage,Time
0,Pineapple Cup 2023,810,Saturday 21-Jan 03:30 PM
1,TCORA WINTER Point Series Regatta 2023-Race2of6,5,Sunday 22-Jan 10:00 AM
2,The Europe Race Hamburg (GER) - Delfzijl (NED) M,65,Sunday 22-Jan 10:10 AM
3,La Réunion Race 2023,108,Monday 23-Jan 03:00 AM
4,The Europe Race Hamburg (GER) - Delfzijl (NED) A,65,Monday 23-Jan 10:30 AM
5,THE OCEAN RACE 2023 - 2 ème Etape,3927,Wednesday 25-Jan 01:00 PM
6,The Europe Race Delfzijl (NED)-Den Helder (NED) M,82,Friday 27-Jan 12:10 PM
7,The Europe Race Delfzijl (NED)-Den Helder (NED) A,82,Friday 27-Jan 12:30 PM
8,The Europe Race Den Helder (NED)-The Hague (NE...,55,Saturday 28-Jan 10:10 AM
9,The Europe Race Den Helder (NED)-The Hague (NE...,55,Saturday 28-Jan 10:30 AM
10,Tasmania Race,643,Saturday 28-Jan 11:00 AM
11,The Europe Race The Hague (NED)-Rotterdam(NED) M,52,Sunday 29-Jan 08:10 AM
12,The Europe Race The Hague (NED)-Rotterdam(NED) A,52,Sunday 29-Jan 08:30 AM
13,Dubai to Muscat Race,305,Saturday 04-Feb 05:00 AM
14,The Europe Race Rotterdam (NED) - Antwerp (BEL) M,43,Saturday 04-Feb 07:10 AM
15,The Europe Race Rotterdam (NED) - Antwerp (BEL) A,43,Saturday 04-Feb 07:30 AM
16,Buenos Aires - Rio de Janeiro,1058,Saturday 04-Feb 01:00 PM

In [11]:
df_short_on_weekends = df[(df['Mileage'] < short_mileage) & (df['Time'].str.contains('Saturday') | df['Time'].str.contains('Sunday'))]

,Race,Mileage,Time
1,TCORA WINTER Point Series Regatta 2023-Race2of6,5,Sunday 22-Jan 10:00 AM
14,The Europe Race Rotterdam (NED) - Antwerp (BEL) M,43,Saturday 04-Feb 07:10 AM
15,The Europe Race Rotterdam (NED) - Antwerp (BEL) A,43,Saturday 04-Feb 07:30 AM

In [12]:
print(df)

,Race,Mileage,Time
0,Pineapple Cup 2023,810,Saturday 21-Jan 03:30 PM
1,TCORA WINTER Point Series Regatta 2023-Race2of6,5,Sunday 22-Jan 10:00 AM
2,The Europe Race Hamburg (GER) - Delfzijl (NED) M,65,Sunday 22-Jan 10:10 AM
3,La Réunion Race 2023,108,Monday 23-Jan 03:00 AM
4,The Europe Race Hamburg (GER) - Delfzijl (NED) A,65,Monday 23-Jan 10:30 AM
5,THE OCEAN RACE 2023 - 2 ème Etape,3927,Wednesday 25-Jan 01:00 PM
6,The Europe Race Delfzijl (NED)-Den Helder (NED) M,82,Friday 27-Jan 12:10 PM
7,The Europe Race Delfzijl (NED)-Den Helder (NED) A,82,Friday 27-Jan 12:30 PM
8,The Europe Race Den Helder (NED)-The Hague (NE...,55,Saturday 28-Jan 10:10 AM
9,The Europe Race Den Helder (NED)-The Hague (NE...,55,Saturday 28-Jan 10:30 AM
10,Tasmania Race,643,Saturday 28-Jan 11:00 AM
11,The Europe Race The Hague (NED)-Rotterdam(NED) M,52,Sunday 29-Jan 08:10 AM
12,The Europe Race The Hague (NED)-Rotterdam(NED) A,52,Sunday 29-Jan 08:30 AM
13,Dubai to Muscat Race,305,Saturday 04-Feb 05:00 AM
14,The Europe Race Rotterdam (NED) - Antwerp (BEL) M,43,Saturday 04-Feb 07:10 AM
15,The Europe Race Rotterdam (NED) - Antwerp (BEL) A,43,Saturday 04-Feb 07:30 AM
16,Buenos Aires - Rio de Janeiro,1058,Saturday 04-Feb 01:00 PM

In [19]:
print('------------------\nShort starting on weekends:\n {}'.format(df_short_on_weekends))

------------------
Short starting on weekends:
                                                  Race  Mileage  \
1     TCORA WINTER Point Series Regatta 2023-Race2of6        5
14  The Europe Race Rotterdam (NED) - Antwerp (BEL) M       43
15  The Europe Race Rotterdam (NED) - Antwerp (BEL) A       43

                        Time
1     Sunday 22-Jan 10:00 AM
14  Saturday 04-Feb 07:10 AM
15  Saturday 04-Feb 07:30 AM